version: "3.7"

services:
  els-elasticsearch:
    image: elasticsearch:7.16.1
    container_name: els-elasticsearch
    environment:
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9211:9200"
      - "9311:9300"
    networks:
      - els-network

  # els-logstash:
  #   image: logstash:7.16.1
  #   container_name: els-logstash
  #   volumes:
  #     - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
  #     - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  #     - ./logstash/logstash.template.json:/usr/share/logstash/templates/logstash.template.json
  #   ports:
  #     - "5144:5044"
  #   depends_on:
  #     - els-elasticsearch
  #   networks:
  #     - els-network

  els-kibana:
    image: kibana:7.16.1
    container_name: els-kibana
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5702:5601"
    depends_on:
      - els-elasticsearch
    networks:
      - els-network

  # Todo: Separate els-filebeat from els-log to allow multi-host deployment
#   els-filebeat:
#     image: docker.elastic.co/beels/filebeat:7.16.1
#     container_name: els-filebeat
#     depends_on:
#       - els-logstash
#     volumes:
#       - els-auth-logs:/usr/share/filebeat/auth-logs
#       - els-auth-store-logs:/usr/share/filebeat/auth-store-logs
#       - els-ui-logs:/usr/share/filebeat/ui-logs
#       - els-job-logs:/usr/share/filebeat/job-logs
#       - els-job-store-logs:/usr/share/filebeat/job-store-logs
#       - els-client-ui-logs:/usr/share/filebeat/client-ui-logs
#       - els-client-logs:/usr/share/filebeat/client-logs
#       - els-client-store-logs:/usr/share/filebeat/client-store-logs
#       - els-opsbot-logs:/usr/share/filebeat/opsbot-logs
#       - els-opsbot-store-logs:/usr/share/filebeat/opsbot-store-logs
# #      - app1_logs:/usr/share/filebeat/app1_logs
#       - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
#       - /var/run/docker.sock:/host_docker/docker.sock
#       - /var/lib/docker:/host_docker/var/lib/docker
#     networks:
#       - els-network

networks:
  els-network:
    name: els-network
    driver: bridge

volumes:
  els-auth-logs:
    name: els-auth-logs
#    external: true
  els-auth-store-logs:
    name: els-auth-store-logs
#    external: true
  els-ui-logs:
    name: els-ui-logs
#    external: true
  els-job-logs:
    name: els-job-logs
#    external: true
  els-job-store-logs:
    name: els-job-store-logs
#    external: true
  els-client-ui-logs:
    name: els-client-ui-logs
#    external: true
  els-client-logs:
    name: els-client-logs
#    external: true
  els-client-store-logs:
    name: els-client-store-logs
#    external: true
  els-opsbot-logs:
    name: els-opsbot-logs
#    external: true
  els-opsbot-store-logs:
    name: els-opsbot-store-logs
#    external: true
#  app1_logs:
#    name: app1_logs
#    external: true